/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param person 
 * @param language 
 */


data class AnimeCharactersDataInnerVoiceActorsInner (

    @SerializedName("person")
    val person: AnimeCharactersDataInnerVoiceActorsInnerPerson? = null,

    @SerializedName("language")
    val language: kotlin.String? = null

)

