/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param openings 
 * @param endings 
 */


data class AnimeFullTheme (

    @SerializedName("openings")
    val openings: List<kotlin.String>? = null,

    @SerializedName("endings")
    val endings: List<kotlin.String>? = null

)

