/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param title Title
 * @param video 
 * @param meta 
 */


data class AnimeVideosDataMusicVideosInner (

    /* Title */
    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("video")
    val video: Trailer? = null,

    @SerializedName("meta")
    val meta: AnimeVideosDataMusicVideosInnerMeta? = null

)

