/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param malId 
 * @param url 
 * @param images 
 * @param name 
 */


data class AnimeCharactersDataInnerVoiceActorsInnerPerson (

    @SerializedName("mal_id")
    val malId: kotlin.Int? = null,

    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("images")
    val images: PeopleImages? = null,

    @SerializedName("name")
    val name: kotlin.String? = null

)

