/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param person 
 * @param positions Staff Positions
 */


data class AnimeStaffDataInner (

    @SerializedName("person")
    val person: AnimeStaffDataInnerPerson? = null,

    /* Staff Positions */
    @SerializedName("positions")
    val positions: kotlin.collections.List<kotlin.String>? = null

)

