/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available Anime order_by properties
 *
 * Values: mal_id,title,start_date,end_date,episodes,score,scored_by,rank,popularity,members,favorites
 */

enum class AnimeSearchQueryOrderby(val value: kotlin.String) {

    @SerializedName(value = "mal_id")
    MAL_ID("mal_id"),

    @SerializedName(value = "title")
    TITLE("title"),

    @SerializedName(value = "start_date")
    START_DATE("start_date"),

    @SerializedName(value = "end_date")
    END_DATE("end_date"),

    @SerializedName(value = "episodes")
    EPISODES("episodes"),

    @SerializedName(value = "score")
    SCORE("score"),

    @SerializedName(value = "scored_by")
    SCORE_BY("scored_by"),

    @SerializedName(value = "rank")
    RANK("rank"),

    @SerializedName(value = "popularity")
    POPULARITY("popularity"),

    @SerializedName(value = "members")
    MEMBERS("members"),

    @SerializedName(value = "favorites")
    FAVORITES("favorites");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AnimeSearchQueryOrderby) "$data" else null

        /**
         * Returns a valid [AnimeSearchQueryOrderby] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AnimeSearchQueryOrderby? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

