/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param score Scoring value
 * @param votes Number of votes for this score
 * @param percentage Percentage of votes for this score
 */


data class AnimeStatisticsDataScoresInner (

    /* Scoring value */
    @SerializedName("score")
    val score: kotlin.Int? = null,

    /* Number of votes for this score */
    @SerializedName("votes")
    val votes: kotlin.Int? = null,

    /* Percentage of votes for this score */
    @SerializedName("percentage")
    val percentage: kotlin.Float? = null

)

