/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available images in WEBP
 *
 * @param imageUrl Image URL WEBP
 * @param smallImageUrl Small Image URL WEBP
 * @param largeImageUrl Image URL WEBP
 */


data class AnimeImagesWebp (

    /* Image URL WEBP */
    @SerializedName("image_url")
    val imageUrl: kotlin.String? = null,

    /* Small Image URL WEBP */
    @SerializedName("small_image_url")
    val smallImageUrl: kotlin.String? = null,

    /* Image URL WEBP */
    @SerializedName("large_image_url")
    val largeImageUrl: kotlin.String? = null

)

