/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param promo 
 * @param episodes 
 * @param musicVideos 
 */


data class AnimeVideosData (

    @SerializedName("promo")
    val promo: kotlin.collections.List<AnimeVideosDataPromoInner>? = null,

    @SerializedName("episodes")
    val episodes: kotlin.collections.List<AnimeVideosDataEpisodesInner>? = null,

    @SerializedName("music_videos")
    val musicVideos: kotlin.collections.List<AnimeVideosDataMusicVideosInner>? = null

)

