/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Anime User Updates Resource
 *
 * @param pagination 
 * @param `data` 
 */


data class AnimeUserupdates (

    @SerializedName("pagination")
    val pagination: PaginationPagination? = null,

    @SerializedName("data")
    val `data`: List<AnimeUserupdatesAllOfData>? = null

)

