/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param score User Score
 * @param status User list status
 * @param episodesSeen Number of episodes seen
 * @param episodesTotal Total number of episodes
 * @param date Last updated date ISO8601
 */


data class AnimeUserupdatesAllOfData (

    @SerializedName("user")
    val user: UserMeta? = null,

    /* User Score */
    @SerializedName("score")
    val score: kotlin.Int? = null,

    /* User list status */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* Number of episodes seen */
    @SerializedName("episodes_seen")
    val episodesSeen: kotlin.Int? = null,

    /* Total number of episodes */
    @SerializedName("episodes_total")
    val episodesTotal: kotlin.Int? = null,

    /* Last updated date ISO8601 */
    @SerializedName("date")
    val date: kotlin.String? = null

)

