/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available Anime audience ratings<br><br><b>Ratings</b><br><ul><li>G - All Ages</li><li>PG - Children</li><li>PG-13 - Teens 13 or older</li><li>R - 17+ (violence & profanity)</li><li>R+ - Mild Nudity</li><li>Rx - Hentai</li></ul>
 *
 * Values: g,pg,pg13,r17,r,rx
 */

enum class AnimeSearchQueryRating(val value: String) {

    @SerializedName(value = "g")
    g("g"),

    @SerializedName(value = "pg")
    pg("pg"),

    @SerializedName(value = "pg13")
    pg13("pg13"),

    @SerializedName(value = "r17")
    r17("r17"),

    @SerializedName(value = "r")
    r("r"),

    @SerializedName(value = "rx")
    rx("rx");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is AnimeSearchQueryRating) "$data" else null

        /**
         * Returns a valid [AnimeSearchQueryRating] for [data], null otherwise.
         */
        fun decode(data: Any?): AnimeSearchQueryRating? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

