/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param title 
 * @param author 
 */


data class AnimeVideosDataMusicVideosInnerMeta (

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("author")
    val author: kotlin.String? = null

)

