/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param relation Relation type
 * @param entry 
 */


data class AnimeFullRelationsInner (

    /* Relation type */
    @SerializedName("relation")
    val relation: kotlin.String? = null,

    @SerializedName("entry")
    val entry: kotlin.collections.List<MalUrl>? = null

)

