/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Broadcast Details
 *
 * @param day Day of the week
 * @param time Time in 24 hour format
 * @param timezone Timezone (Tz Database format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
 * @param string Raw parsed broadcast string
 */


data class Broadcast (

    /* Day of the week */
    @SerializedName("day")
    val day: kotlin.String? = null,

    /* Time in 24 hour format */
    @SerializedName("time")
    val time: kotlin.String? = null,

    /* Timezone (Tz Database format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) */
    @SerializedName("timezone")
    val timezone: kotlin.String? = null,

    /* Raw parsed broadcast string */
    @SerializedName("string")
    val string: kotlin.String? = null

)

