/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Character Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param images 
 * @param name Name
 * @param nameKanji Name
 * @param nicknames Other Names
 * @param favorites Number of users who have favorited this entry
 * @param about Biography
 * @param anime 
 * @param manga 
 * @param voices 
 */


data class CharacterFull (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: String? = null,

    @SerializedName("images")
    val images: CharacterImages? = null,

    /* Name */
    @SerializedName("name")
    val name: String? = null,

    /* Name */
    @SerializedName("name_kanji")
    val nameKanji: String? = null,

    /* Other Names */
    @SerializedName("nicknames")
    val nicknames: List<kotlin.String>? = null,

    /* Number of users who have favorited this entry */
    @SerializedName("favorites")
    val favorites: Int? = null,

    /* Biography */
    @SerializedName("about")
    val about: String? = null,

    @SerializedName("anime")
    val anime: List<CharacterAnimeDataInner>? = null,

    @SerializedName("manga")
    val manga: List<CharacterFullMangaInner>? = null,

    @SerializedName("voices")
    val voices: List<CharacterFullVoicesInner>? = null

)

