/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param language Character's Role
 * @param person 
 */


data class CharacterFullVoicesInner (

    /* Character's Role */
    @SerializedName("language")
    val language: kotlin.String? = null,

    @SerializedName("person")
    val person: PersonMeta? = null

)

