/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param imageUrl Default JPG Image Size URL
 * @param largeImageUrl Large JPG Image Size URL
 */


data class CharacterPicturesDataInner (

    /* Default JPG Image Size URL */
    @SerializedName("image_url")
    val imageUrl: kotlin.String? = null,

    /* Large JPG Image Size URL */
    @SerializedName("large_image_url")
    val largeImageUrl: kotlin.String? = null

)

