/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Club Search Query Category
 *
 * Values: anime,manga,actors_and_artists,characters,cities_and_neighborhoods,companies,conventions,games,japan,music,other,schools
 */

enum class ClubSearchQueryCategory(val value: kotlin.String) {

    @SerializedName(value = "anime")
    anime("anime"),

    @SerializedName(value = "manga")
    manga("manga"),

    @SerializedName(value = "actors_and_artists")
    actors_and_artists("actors_and_artists"),

    @SerializedName(value = "characters")
    characters("characters"),

    @SerializedName(value = "cities_and_neighborhoods")
    cities_and_neighborhoods("cities_and_neighborhoods"),

    @SerializedName(value = "companies")
    companies("companies"),

    @SerializedName(value = "conventions")
    conventions("conventions"),

    @SerializedName(value = "games")
    games("games"),

    @SerializedName(value = "japan")
    japan("japan"),

    @SerializedName(value = "music")
    music("music"),

    @SerializedName(value = "other")
    other("other"),

    @SerializedName(value = "schools")
    schools("schools");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ClubSearchQueryCategory) "$data" else null

        /**
         * Returns a valid [ClubSearchQueryCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ClubSearchQueryCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

