/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Club Search Query Type
 *
 * Values: `public`,`private`,secret
 */

enum class ClubSearchQueryType(val value: String) {

    @SerializedName(value = "public")
    `public`("public"),

    @SerializedName(value = "private")
    `private`("private"),

    @SerializedName(value = "secret")
    secret("secret");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is ClubSearchQueryType) "$data" else null

        /**
         * Returns a valid [ClubSearchQueryType] for [data], null otherwise.
         */
        fun decode(data: Any?): ClubSearchQueryType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

