/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url User URL
 * @param username User's username
 */


data class ClubStaffDataInner (

    /* User URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* User's username */
    @SerializedName("username")
    val username: kotlin.String? = null

)

