/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username User's username
 * @param url User URL
 * @param images 
 */


data class ClubMemberDataInner (

    /* User's username */
    @SerializedName("username")
    val username: String? = null,

    /* User URL */
    @SerializedName("url")
    val url: String? = null,

    @SerializedName("images")
    val images: UserImages? = null

)

