/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param anime 
 * @param manga 
 * @param characters 
 */


data class ClubRelationsData (

    @SerializedName("anime")
    val anime: List<MalUrl>? = null,

    @SerializedName("manga")
    val manga: List<MalUrl>? = null,

    @SerializedName("characters")
    val characters: List<MalUrl>? = null

)

