/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Club Resource
 *
 * @param malId MyAnimeList ID
 * @param name Club name
 * @param url Club URL
 * @param images 
 * @param members Number of club members
 * @param category Club Category
 * @param created Date Created ISO8601
 * @param access Club access
 */


data class Club (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: Int? = null,

    /* Club name */
    @SerializedName("name")
    val name: String? = null,

    /* Club URL */
    @SerializedName("url")
    val url: String? = null,

    @SerializedName("images")
    val images: CommonImages? = null,

    /* Number of club members */
    @SerializedName("members")
    val members: Int? = null,

    /* Club Category */
    @SerializedName("category")
    val category: Club.Category? = null,

    /* Date Created ISO8601 */
    @SerializedName("created")
    val created: String? = null,

    /* Club access */
    @SerializedName("access")
    val access: Club.Access? = null

) {

    /**
     * Club Category
     *
     * Values: actors_Ampersand_artists,anime,characters,cities_Ampersand_neighborhoods,companies,conventions,games,japan,manga,music,others,schools
     */
    enum class Category(val value: String) {
        @SerializedName(value = "actors & artists") actors_Ampersand_artists("actors & artists"),
        @SerializedName(value = "anime") anime("anime"),
        @SerializedName(value = "characters") characters("characters"),
        @SerializedName(value = "cities & neighborhoods") cities_Ampersand_neighborhoods("cities & neighborhoods"),
        @SerializedName(value = "companies") companies("companies"),
        @SerializedName(value = "conventions") conventions("conventions"),
        @SerializedName(value = "games") games("games"),
        @SerializedName(value = "japan") japan("japan"),
        @SerializedName(value = "manga") manga("manga"),
        @SerializedName(value = "music") music("music"),
        @SerializedName(value = "others") others("others"),
        @SerializedName(value = "schools") schools("schools");
    }
    /**
     * Club access
     *
     * Values: `public`,`private`,secret
     */
    enum class Access(val value: String) {
        @SerializedName(value = "public") `public`("public"),
        @SerializedName(value = "private") `private`("private"),
        @SerializedName(value = "secret") secret("secret");
    }

}

