/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Date Prop From
 *
 * @param day Day
 * @param month Month
 * @param year Year
 */


data class DaterangePropFrom (

    /* Day */
    @SerializedName("day")
    val day: kotlin.Int? = null,

    /* Month */
    @SerializedName("month")
    val month: kotlin.Int? = null,

    /* Year */
    @SerializedName("year")
    val year: kotlin.Int? = null

)

