/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Entry Meta data
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param imageUrl Image URL
 * @param name Entry Name/Title
 */


data class EntryMeta (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: String? = null,

    /* Image URL */
    @SerializedName("image_url")
    val imageUrl: String? = null,

    /* Entry Name/Title */
    @SerializedName("name")
    val name: String? = null

)

