/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param title Title
 * @param date Post Date ISO8601
 * @param authorUsername Author MyAnimeList Username
 * @param authorUrl Author Profile URL
 * @param comments Comment count
 * @param lastComment 
 */


data class ForumDataInner (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* Title */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* Post Date ISO8601 */
    @SerializedName("date")
    val date: kotlin.String? = null,

    /* Author MyAnimeList Username */
    @SerializedName("author_username")
    val authorUsername: kotlin.String? = null,

    /* Author Profile URL */
    @SerializedName("author_url")
    val authorUrl: kotlin.String? = null,

    /* Comment count */
    @SerializedName("comments")
    val comments: kotlin.Int? = null,

    @SerializedName("last_comment")
    val lastComment: ForumDataInnerLastComment? = null

)

