/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Last comment details
 *
 * @param url Last comment URL
 * @param authorUsername Author MyAnimeList Username
 * @param authorUrl Author Profile URL
 * @param date Last comment date posted ISO8601
 */


data class ForumDataInnerLastComment (

    /* Last comment URL */
    @SerializedName("url")
    val url: String? = null,

    /* Author MyAnimeList Username */
    @SerializedName("author_username")
    val authorUsername: String? = null,

    /* Author Profile URL */
    @SerializedName("author_url")
    val authorUrl: String? = null,

    /* Last comment date posted ISO8601 */
    @SerializedName("date")
    val date: String? = null

)

