/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Parsed URL Data
 *
 * @param malId MyAnimeList ID
 * @param type Type of resource
 * @param name Resource Name/Title
 * @param url MyAnimeList URL
 */


data class MalUrl (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: Int? = null,

    /* Type of resource */
    @SerializedName("type")
    val type: String? = null,

    /* Resource Name/Title */
    @SerializedName("name")
    val name: String? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: String? = null

)

