/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available Manga statuses
 *
 * Values: publishing,complete,hiatus,discontinued,upcoming
 */

enum class MangaSearchQueryStatus(val value: kotlin.String) {

    @SerializedName(value = "publishing")
    publishing("publishing"),

    @SerializedName(value = "complete")
    complete("complete"),

    @SerializedName(value = "hiatus")
    hiatus("hiatus"),

    @SerializedName(value = "discontinued")
    discontinued("discontinued"),

    @SerializedName(value = "upcoming")
    upcoming("upcoming");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MangaSearchQueryStatus) "$data" else null

        /**
         * Returns a valid [MangaSearchQueryStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MangaSearchQueryStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

