/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * User reaction count on the review
 *
 * @param overall Overall reaction count
 * @param nice Nice reaction count
 * @param loveIt Love it reaction count
 * @param funny Funny reaction count
 * @param confusing Confusing reaction count
 * @param informative Informative reaction count
 * @param wellWritten Well written reaction count
 * @param creative Creative reaction count
 */


data class MangaReviewReactions (

    /* Overall reaction count */
    @SerializedName("overall")
    val overall: kotlin.Int? = null,

    /* Nice reaction count */
    @SerializedName("nice")
    val nice: kotlin.Int? = null,

    /* Love it reaction count */
    @SerializedName("love_it")
    val loveIt: kotlin.Int? = null,

    /* Funny reaction count */
    @SerializedName("funny")
    val funny: kotlin.Int? = null,

    /* Confusing reaction count */
    @SerializedName("confusing")
    val confusing: kotlin.Int? = null,

    /* Informative reaction count */
    @SerializedName("informative")
    val informative: kotlin.Int? = null,

    /* Well written reaction count */
    @SerializedName("well_written")
    val wellWritten: kotlin.Int? = null,

    /* Creative reaction count */
    @SerializedName("creative")
    val creative: kotlin.Int? = null

)

