/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param score User Score
 * @param status User list status
 * @param volumesRead Number of volumes read
 * @param volumesTotal Total number of volumes
 * @param chaptersRead Number of chapters read
 * @param chaptersTotal Total number of chapters
 * @param date Last updated date ISO8601
 */


data class MangaUserupdatesAllOfData (

    @SerializedName("user")
    val user: UserMeta? = null,

    /* User Score */
    @SerializedName("score")
    val score: kotlin.Int? = null,

    /* User list status */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* Number of volumes read */
    @SerializedName("volumes_read")
    val volumesRead: kotlin.Int? = null,

    /* Total number of volumes */
    @SerializedName("volumes_total")
    val volumesTotal: kotlin.Int? = null,

    /* Number of chapters read */
    @SerializedName("chapters_read")
    val chaptersRead: kotlin.Int? = null,

    /* Total number of chapters */
    @SerializedName("chapters_total")
    val chaptersTotal: kotlin.Int? = null,

    /* Last updated date ISO8601 */
    @SerializedName("date")
    val date: kotlin.String? = null

)

