/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param count 
 * @param total 
 * @param perPage 
 */


data class PaginationPlusPaginationItems (

    @SerializedName("count")
    val count: kotlin.Int? = null,

    @SerializedName("total")
    val total: kotlin.Int? = null,

    @SerializedName("per_page")
    val perPage: kotlin.Int? = null

)

