/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param role Person's Character's role in the anime
 * @param anime 
 * @param character 
 */


data class PersonFullVoicesInner (

    /* Person's Character's role in the anime */
    @SerializedName("role")
    val role: String? = null,

    @SerializedName("anime")
    val anime: AnimeMeta? = null,

    @SerializedName("character")
    val character: CharacterMeta? = null

)

