/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param position Person's position
 * @param manga 
 */


data class PersonFullMangaInner (

    /* Person's position */
    @SerializedName("position")
    val position: String? = null,

    @SerializedName("manga")
    val manga: MangaMeta? = null

)

