/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Person Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param websiteUrl Person's website URL
 * @param images 
 * @param name Name
 * @param givenName Given Name
 * @param familyName Family Name
 * @param alternateNames Other Names
 * @param birthday Birthday Date ISO8601
 * @param favorites Number of users who have favorited this entry
 * @param about Biography
 * @param anime 
 * @param manga 
 * @param voices 
 */


data class PersonFull (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* Person's website URL */
    @SerializedName("website_url")
    val websiteUrl: kotlin.String? = null,

    @SerializedName("images")
    val images: PeopleImages? = null,

    /* Name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Given Name */
    @SerializedName("given_name")
    val givenName: kotlin.String? = null,

    /* Family Name */
    @SerializedName("family_name")
    val familyName: kotlin.String? = null,

    /* Other Names */
    @SerializedName("alternate_names")
    val alternateNames: kotlin.collections.List<kotlin.String>? = null,

    /* Birthday Date ISO8601 */
    @SerializedName("birthday")
    val birthday: kotlin.String? = null,

    /* Number of users who have favorited this entry */
    @SerializedName("favorites")
    val favorites: kotlin.Int? = null,

    /* Biography */
    @SerializedName("about")
    val about: kotlin.String? = null,

    @SerializedName("anime")
    val anime: kotlin.collections.List<PersonAnimeDataInner>? = null,

    @SerializedName("manga")
    val manga: kotlin.collections.List<PersonFullMangaInner>? = null,

    @SerializedName("voices")
    val voices: kotlin.collections.List<PersonFullVoicesInner>? = null

)

