/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Producers Resource
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param titles All titles
 * @param images 
 * @param favorites Producers's member favorites count
 * @param count Producers's anime count
 * @param established Established Date ISO8601
 * @param about About the Producer
 */


data class Producer (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: kotlin.Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* All titles */
    @SerializedName("titles")
    val titles: kotlin.collections.List<Title>? = null,

    @SerializedName("images")
    val images: CommonImages? = null,

    /* Producers's member favorites count */
    @SerializedName("favorites")
    val favorites: kotlin.Int? = null,

    /* Producers's anime count */
    @SerializedName("count")
    val count: kotlin.Int? = null,

    /* Established Date ISO8601 */
    @SerializedName("established")
    val established: kotlin.String? = null,

    /* About the Producer */
    @SerializedName("about")
    val about: kotlin.String? = null

)

