/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import org.openapitools.network.models.AnyOfLessThanAnimeMetaCommaMangaMetaGreaterThan

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param malId MAL IDs of recommendations is both of the MAL ID's with a `-` delimiter
 * @param entry Array of 2 entries that are being recommended to each other
 * @param content Recommendation context provided by the user
 * @param user 
 */


data class RecommendationsAllOfData (

    /* MAL IDs of recommendations is both of the MAL ID's with a `-` delimiter */
    @SerializedName("mal_id")
    val malId: kotlin.String? = null,

    /* Array of 2 entries that are being recommended to each other */
    @SerializedName("entry")
    val entry: kotlin.collections.List<AnyOfLessThanAnimeMetaCommaMangaMetaGreaterThan>? = null,

    /* Recommendation context provided by the user */
    @SerializedName("content")
    val content: kotlin.String? = null,

    @SerializedName("user")
    val user: UserById? = null

)

