/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Related resources
 *
 * @param relation Relation type
 * @param entry Related entries
 */


data class Relation (

    /* Relation type */
    @SerializedName("relation")
    val relation: String? = null,

    /* Related entries */
    @SerializedName("entry")
    val entry: List<MalUrl>? = null

)

