/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param year Year
 * @param seasons List of available seasons
 */


data class SeasonsDataInner (

    /* Year */
    @SerializedName("year")
    val year: Int? = null,

    /* List of available seasons */
    @SerializedName("seasons")
    val seasons: List<kotlin.String>? = null

)

