/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * The type of reviews to filter by. Defaults to anime.
 *
 * Values: anime,manga
 */

enum class TopReviewsTypeEnum(val value: String) {

    @SerializedName(value = "anime")
    anime("anime"),

    @SerializedName(value = "manga")
    manga("manga");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is TopReviewsTypeEnum) "$data" else null

        /**
         * Returns a valid [TopReviewsTypeEnum] for [data], null otherwise.
         */
        fun decode(data: Any?): TopReviewsTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

