/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param imageUrl Default Image Size URL (120x90)
 * @param smallImageUrl Small Image Size URL (640x480)
 * @param mediumImageUrl Medium Image Size URL (320x180)
 * @param largeImageUrl Large Image Size URL (480x360)
 * @param maximumImageUrl Maximum Image Size URL (1280x720)
 */


data class TrailerImagesImages (

    /* Default Image Size URL (120x90) */
    @SerializedName("image_url")
    val imageUrl: kotlin.String? = null,

    /* Small Image Size URL (640x480) */
    @SerializedName("small_image_url")
    val smallImageUrl: kotlin.String? = null,

    /* Medium Image Size URL (320x180) */
    @SerializedName("medium_image_url")
    val mediumImageUrl: kotlin.String? = null,

    /* Large Image Size URL (480x360) */
    @SerializedName("large_image_url")
    val largeImageUrl: kotlin.String? = null,

    /* Maximum Image Size URL (1280x720) */
    @SerializedName("maximum_image_url")
    val maximumImageUrl: kotlin.String? = null

)

