/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Anime Statistics
 *
 * @param daysWatched Number of days spent watching Anime
 * @param meanScore Mean Score
 * @param watching Anime Watching
 * @param completed Anime Completed
 * @param onHold Anime On-Hold
 * @param dropped Anime Dropped
 * @param planToWatch Anime Planned to Watch
 * @param totalEntries Total Anime entries on User list
 * @param rewatched Anime re-watched
 * @param episodesWatched Number of Anime Episodes Watched
 */


data class UserProfileFullStatisticsAnime (

    /* Number of days spent watching Anime */
    @SerializedName("days_watched")
    val daysWatched: Float? = null,

    /* Mean Score */
    @SerializedName("mean_score")
    val meanScore: Float? = null,

    /* Anime Watching */
    @SerializedName("watching")
    val watching: Int? = null,

    /* Anime Completed */
    @SerializedName("completed")
    val completed: Int? = null,

    /* Anime On-Hold */
    @SerializedName("on_hold")
    val onHold: Int? = null,

    /* Anime Dropped */
    @SerializedName("dropped")
    val dropped: Int? = null,

    /* Anime Planned to Watch */
    @SerializedName("plan_to_watch")
    val planToWatch: Int? = null,

    /* Total Anime entries on User list */
    @SerializedName("total_entries")
    val totalEntries: Int? = null,

    /* Anime re-watched */
    @SerializedName("rewatched")
    val rewatched: Int? = null,

    /* Number of Anime Episodes Watched */
    @SerializedName("episodes_watched")
    val episodesWatched: Int? = null

)

