/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username MyAnimeList Username
 * @param url MyAnimeList Profile URL
 * @param images 
 */


data class UserMeta (

    /* MyAnimeList Username */
    @SerializedName("username")
    val username: kotlin.String? = null,

    /* MyAnimeList Profile URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("images")
    val images: UserImages? = null

)

