/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Users Search Query Gender.
 *
 * Values: any,male,female,nonbinary
 */

enum class UsersSearchQueryGender(val value: String) {

    @SerializedName(value = "any")
    any("any"),

    @SerializedName(value = "male")
    male("male"),

    @SerializedName(value = "female")
    female("female"),

    @SerializedName(value = "nonbinary")
    nonbinary("nonbinary");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is UsersSearchQueryGender) "$data" else null

        /**
         * Returns a valid [UsersSearchQueryGender] for [data], null otherwise.
         */
        fun decode(data: Any?): UsersSearchQueryGender? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

