/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available images in JPG
 *
 * @param imageUrl Image URL JPG (225x335)
 */


data class UsersTempDataInnerImagesJpg (

    /* Image URL JPG (225x335) */
    @SerializedName("image_url")
    val imageUrl: kotlin.String? = null

)

