/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * User Meta By ID
 *
 * @param url MyAnimeList URL
 * @param username MyAnimeList Username
 */


data class UserById (

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* MyAnimeList Username */
    @SerializedName("username")
    val username: kotlin.String? = null

)

