/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entry 
 * @param score 
 * @param status 
 * @param episodesSeen 
 * @param episodesTotal 
 * @param date ISO8601 format
 */


data class UserUpdatesDataAnimeInner (

    @SerializedName("entry")
    val entry: AnimeMeta? = null,

    @SerializedName("score")
    val score: kotlin.Int? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("episodes_seen")
    val episodesSeen: kotlin.Int? = null,

    @SerializedName("episodes_total")
    val episodesTotal: kotlin.Int? = null,

    /* ISO8601 format */
    @SerializedName("date")
    val date: kotlin.String? = null

)

