/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * Available images in WEBP
 *
 * @param imageUrl Image URL WEBP
 */


data class UserImagesWebp (

    /* Image URL WEBP */
    @SerializedName("image_url")
    val imageUrl: String? = null

)

