/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param images 
 * @param title Entry title
 * @param type 
 * @param startYear 
 */


data class UserFavoritesMangaInner (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: Int? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: String? = null,

    @SerializedName("images")
    val images: MangaImages? = null,

    /* Entry title */
    @SerializedName("title")
    val title: String? = null,

    @SerializedName("type")
    val type: String? = null,

    @SerializedName("start_year")
    val startYear: Int? = null

)

