/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param anime Last updated Anime
 * @param manga Last updated Manga
 */


data class UserUpdatesData (

    /* Last updated Anime */
    @SerializedName("anime")
    val anime: kotlin.collections.List<UserUpdatesDataAnimeInner>? = null,

    /* Last updated Manga */
    @SerializedName("manga")
    val manga: kotlin.collections.List<UserUpdatesDataMangaInner>? = null

)

