/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param anime 
 * @param manga 
 */


data class UserProfileFullStatistics (

    @SerializedName("anime")
    val anime: UserProfileFullStatisticsAnime? = null,

    @SerializedName("manga")
    val manga: UserProfileFullStatisticsManga? = null

)

