/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param lastOnline Last Online Date ISO8601 format
 * @param friendsSince Friends Since Date ISO8601 format
 */


data class UserFriendsAllOfDataInner (

    @SerializedName("user")
    val user: UserMeta? = null,

    /* Last Online Date ISO8601 format */
    @SerializedName("last_online")
    val lastOnline: String? = null,

    /* Friends Since Date ISO8601 format */
    @SerializedName("friends_since")
    val friendsSince: String? = null

)

