/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Favorite entries
 *
 * @param anime Favorite Anime
 * @param manga Favorite Manga
 * @param characters Favorite Characters
 * @param people Favorite People
 */


data class UsersTempDataInnerFavorites (

    /* Favorite Anime */
    @SerializedName("anime")
    val anime: kotlin.collections.List<EntryMeta>? = null,

    /* Favorite Manga */
    @SerializedName("manga")
    val manga: kotlin.collections.List<EntryMeta>? = null,

    /* Favorite Characters */
    @SerializedName("characters")
    val characters: kotlin.collections.List<EntryMeta>? = null,

    /* Favorite People */
    @SerializedName("people")
    val people: kotlin.collections.List<EntryMeta>? = null

)

