/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entry 
 * @param score 
 * @param status 
 * @param chaptersRead 
 * @param chaptersTotal 
 * @param volumesRead 
 * @param volumesTotal 
 * @param date ISO8601 format
 */


data class UserUpdatesDataMangaInner (

    @SerializedName("entry")
    val entry: MangaMeta? = null,

    @SerializedName("score")
    val score: Int? = null,

    @SerializedName("status")
    val status: String? = null,

    @SerializedName("chapters_read")
    val chaptersRead: Int? = null,

    @SerializedName("chapters_total")
    val chaptersTotal: Int? = null,

    @SerializedName("volumes_read")
    val volumesRead: Int? = null,

    @SerializedName("volumes_total")
    val volumesTotal: Int? = null,

    /* ISO8601 format */
    @SerializedName("date")
    val date: String? = null

)

