/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entry 
 * @param episodes Recent Episodes (max 2 listed)
 * @param regionLocked Region Locked Episode
 */


data class WatchEpisodesAllOfData (

    @SerializedName("entry")
    val entry: AnimeMeta? = null,

    /* Recent Episodes (max 2 listed) */
    @SerializedName("episodes")
    val episodes: List<WatchEpisodesAllOfEpisodes>? = null,

    /* Region Locked Episode */
    @SerializedName("region_locked")
    val regionLocked: Boolean? = null

)

