/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param malId MyAnimeList ID
 * @param url MyAnimeList URL
 * @param title Episode Title
 * @param premium For MyAnimeList Premium Users
 */


data class WatchEpisodesAllOfEpisodes (

    /* MyAnimeList ID */
    @SerializedName("mal_id")
    val malId: kotlin.String? = null,

    /* MyAnimeList URL */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* Episode Title */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* For MyAnimeList Premium Users */
    @SerializedName("premium")
    val premium: kotlin.Boolean? = null

)

