/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.network.models

import com.google.gson.annotations.SerializedName

/**
 * Watch Promos
 *
 * @param pagination 
 * @param title Promo Title
 * @param `data` 
 */


data class WatchPromos (

    @SerializedName("pagination")
    val pagination: PaginationPagination? = null,

    /* Promo Title */
    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("data")
    val `data`: kotlin.collections.List<kotlin.Any>? = null

)

